version: "3.6"

services:
  build:
    build:
      context: .
    environment:
      - API_URL=${API_URL}
    volumes:
      - ./dist:/dist
    command: npm run build
  jest:
    build:
      context: .
    command: npm run test
