version: "3.6"

services:
  sgbouncewizard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: "http://localhost:3000"
    ports:
      - "80:80"

  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    depends_on:
      - sgbouncewizard
    network_mode: "host"
